### ISSUE TITLE
Need some clarification on Menees.Diffs.Windows.Forms.DiffControl

### ISSUE THREAD

**Issue by arokiavinoth** [menees/Libraries#1]
Below is my code,

Menees.Diffs.Windows.Forms.DiffControl f = new Menees.Diffs.Windows.Forms.DiffControl();
f.showtoolbar= true;
f.size = new size(500, 500);
f.setData(list<string>, list<string>, EditScript);

in the above code, I do know what is EditScript, How to pass ?

I have two list of strings. I have to compare using diffcontrol.

Can you help ?

**Comment by menees** [comment]
My [Diff.Net](https://github.com/menees/Diff.Net/) project is the primary example. Look at [lines 81 - 102 in FileDiffForm.cs](https://github.com/menees/Diff.Net/blob/4342a2db17d9b51800c641dbac14b142f683c9b6/src/Diff.Net/FileDiffForm.cs#L81). Basically, you need to create a TextDiff instance, call Execute on it, and pass in your two lists. Execute returns an EditScript instance.

**Comment by arokiavinoth** [comment]
Hi Bill,
Thank you so much. It helped me a lot.
